name: 'Generate Prerelease Version'
description: 'Generate semantic version (patch increment) with prerelease suffix'
branding:
  icon: 'tag'
  color: 'blue'
inputs:
  suffix:
    description: 'Prerelease suffix (e.g., rc, alpha, beta)'
    required: false
    default: 'rc'

outputs:
  version:
    description: 'The prerelease version (e.g., v1.2.3-rc)'
    value: ${{ steps.generate.outputs.version }}

runs:
  using: 'composite'
  steps:
        
    - name: Generate Semantic Version
      id: generate
      shell: pwsh
      run: |
        & "${{ github.action_path }}/action.ps1" `
          -PrereleaseSuffix '${{ inputs.suffix }}'